version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network
  php:
    image: php:8.2-fpm
    container_name: php-container
    volumes:
      - ../project:/var/www/html
    networks:
      - app_network
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ../project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app_network
  frontend:
    ports:
      - "3000:3000"
    build:
      context: ../frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: react-frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - app_network
volumes:
  db_data:

networks:
  app_network: